# Generated by Django 5.2.11 on 2026-02-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tackle', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaughtFish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('length', models.FloatField(verbose_name='Длина (см)')),
                ('caught_at', models.DateTimeField(auto_now_add=True, verbose_name='Время поимки')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Продана')),
                ('is_released', models.BooleanField(default=False, verbose_name='Отпущена')),
                ('is_record', models.BooleanField(default=False, verbose_name='Рекорд')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.location', verbose_name='Локация')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caught_fish', to='accounts.player')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tackle.fishspecies', verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Пойманная рыба',
                'verbose_name_plural': 'Пойманные рыбы',
                'ordering': ['-caught_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerRod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bait_remaining', models.IntegerField(default=0, verbose_name='Осталось наживки')),
                ('durability_current', models.IntegerField(default=100, verbose_name='Текущая прочность')),
                ('is_assembled', models.BooleanField(default=False, verbose_name='Собрана')),
                ('depth_setting', models.FloatField(default=1.5, verbose_name='Глубина (м)')),
                ('retrieve_speed', models.IntegerField(default=5, verbose_name='Скорость проводки (1-10)')),
                ('bait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tackle.bait', verbose_name='Наживка')),
                ('float_tackle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tackle.floattackle', verbose_name='Поплавок')),
                ('hook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tackle.hook', verbose_name='Крючок')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tackle.line', verbose_name='Леска')),
                ('lure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tackle.lure', verbose_name='Приманка')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rods', to='accounts.player')),
                ('reel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tackle.reel', verbose_name='Катушка')),
                ('rod_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tackle.rodtype', verbose_name='Удилище')),
            ],
            options={
                'verbose_name': 'Снасть игрока',
                'verbose_name_plural': 'Снасти игроков',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='accounts.player')),
            ],
            options={
                'verbose_name': 'Предмет инвентаря',
                'verbose_name_plural': 'Предметы инвентаря',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='inventory_i_content_b01f37_idx')],
            },
        ),
    ]
