# Generated by Django 5.2.11 on 2026-02-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrod',
            name='custom_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Название сборки'),
        ),
    ]
