# Generated by Django 5.2.11 on 2026-02-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_playerrod_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrod',
            name='clip_distance',
            field=models.FloatField(default=30.0, verbose_name='Клипса - дистанция заброса (м)'),
        ),
    ]
