# Generated by Django 5.2.11 on 2026-02-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_playerrod_clip_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerrod',
            name='lure',
        ),
        migrations.RemoveField(
            model_name='playerrod',
            name='retrieve_speed',
        ),
    ]
