# Generated by Django 5.2.11 on 2026-02-18 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_player_rod_slot_1_player_rod_slot_2_and_more'),
        ('tackle', '0003_fishpricedynamic'),
        ('world', '0002_location_travel_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.IntegerField(verbose_name='Требуемое количество')),
                ('min_weight_grams', models.IntegerField(verbose_name='Мин. вес одной рыбы (г)')),
                ('reward_per_fish', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Награда за штуку')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('activated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время активации')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_orders', to='world.location', verbose_name='Локация')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tackle.fishspecies', verbose_name='Вид рыбы')),
            ],
            options={
                'verbose_name': 'Заказ кафе',
                'verbose_name_plural': 'Заказы кафе',
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='CafeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delivered', models.IntegerField(default=0, verbose_name='Сдано штук')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_deliveries', to='accounts.player', verbose_name='Игрок')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='cafe.cafeorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Сдача рыбы в кафе',
                'verbose_name_plural': 'Сдачи рыбы в кафе',
                'unique_together': {('order', 'player')},
            },
        ),
    ]
