# Generated by Django 5.2.11 on 2026-02-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarineStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'Красная'), ('orange', 'Оранжевая'), ('yellow', 'Жёлтая'), ('green', 'Зелёная'), ('blue', 'Синяя'), ('purple', 'Фиолетовая')], max_length=10, unique=True, verbose_name='Цвет')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('drop_chance', models.FloatField(default=0.05, verbose_name='Шанс выпадения (0-1)')),
                ('image', models.ImageField(blank=True, upload_to='stars/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Морская звезда',
                'verbose_name_plural': 'Морские звёзды',
            },
        ),
        migrations.CreateModel(
            name='Potion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='potions/', verbose_name='Изображение')),
                ('effect_type', models.CharField(choices=[('luck', 'Удача'), ('invisibility', 'Невидимость'), ('treasure', 'Клад'), ('rarity', 'Редкость'), ('rank_boost', 'Разряд'), ('trophy', 'Трофей')], max_length=20, verbose_name='Тип эффекта')),
                ('effect_value', models.FloatField(default=1.0, verbose_name='Сила эффекта')),
                ('karma_cost', models.IntegerField(default=50, verbose_name='Стоимость в карме')),
                ('duration_hours', models.IntegerField(default=6, verbose_name='Длительность (игр. часов)')),
                ('required_stars', models.JSONField(default=dict, help_text='{"red": 3, "blue": 2}', verbose_name='Необходимые звёзды')),
                ('is_one_time', models.BooleanField(default=False, verbose_name='Одноразовое')),
            ],
            options={
                'verbose_name': 'Зелье',
                'verbose_name_plural': 'Зелья',
                'ordering': ['karma_cost'],
            },
        ),
        migrations.CreateModel(
            name='PlayerPotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at_hour', models.IntegerField(verbose_name='Час активации (игровой)')),
                ('activated_at_day', models.IntegerField(verbose_name='День активации (игровой)')),
                ('expires_at_hour', models.IntegerField(verbose_name='Час истечения (игровой)')),
                ('expires_at_day', models.IntegerField(verbose_name='День истечения (игровой)')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_potions', to='accounts.player')),
                ('potion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potions.potion')),
            ],
            options={
                'verbose_name': 'Активное зелье',
                'verbose_name_plural': 'Активные зелья',
            },
        ),
        migrations.CreateModel(
            name='PlayerStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='accounts.player')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potions.marinestar')),
            ],
            options={
                'verbose_name': 'Звезда игрока',
                'verbose_name_plural': 'Звёзды игроков',
                'unique_together': {('player', 'star')},
            },
        ),
    ]
