# Generated by Django 5.2.11 on 2026-02-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (рус)')),
                ('name_latin', models.CharField(blank=True, max_length=100, verbose_name='Название (лат)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='fish/', verbose_name='Изображение')),
                ('weight_min', models.FloatField(verbose_name='Мин. вес (кг)')),
                ('weight_max', models.FloatField(verbose_name='Макс. вес (кг)')),
                ('length_min', models.FloatField(verbose_name='Мин. длина (см)')),
                ('length_max', models.FloatField(verbose_name='Макс. длина (см)')),
                ('rarity', models.CharField(choices=[('common', 'Обычная'), ('uncommon', 'Необычная'), ('rare', 'Редкая'), ('trophy', 'Трофейная'), ('legendary', 'Легендарная')], default='common', max_length=20, verbose_name='Редкость')),
                ('sell_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за кг')),
                ('experience_per_kg', models.IntegerField(default=10, verbose_name='Опыт за кг')),
                ('active_time', models.JSONField(default=dict, help_text='{"morning": 0.8, "day": 0.3, "evening": 0.9, "night": 0.5}', verbose_name='Активность по времени суток')),
                ('preferred_depth_min', models.FloatField(default=0.5, verbose_name='Мин. глубина обитания (м)')),
                ('preferred_depth_max', models.FloatField(default=5.0, verbose_name='Макс. глубина обитания (м)')),
            ],
            options={
                'verbose_name': 'Вид рыбы',
                'verbose_name_plural': 'Виды рыб',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='FloatTackle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='tackle/floats/', verbose_name='Изображение')),
                ('capacity', models.FloatField(verbose_name='Грузоподъёмность (г)')),
                ('sensitivity', models.IntegerField(default=5, verbose_name='Чувствительность (1-10)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Поплавок',
                'verbose_name_plural': 'Поплавки',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='food/', verbose_name='Изображение')),
                ('satiety', models.IntegerField(default=20, verbose_name='Сытость')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Еда',
                'verbose_name_plural': 'Еда',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('size', models.IntegerField(verbose_name='Размер')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Крючок',
                'verbose_name_plural': 'Крючки',
                'ordering': ['size'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='tackle/lines/', verbose_name='Изображение')),
                ('breaking_strength', models.FloatField(verbose_name='Прочность на разрыв (кг)')),
                ('thickness', models.FloatField(verbose_name='Толщина (мм)')),
                ('length', models.IntegerField(default=100, verbose_name='Длина (м)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Леска',
                'verbose_name_plural': 'Лески',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='tackle/reels/', verbose_name='Изображение')),
                ('drag_power', models.FloatField(verbose_name='Тяга (кг)')),
                ('line_capacity', models.IntegerField(verbose_name='Вместимость лески (м)')),
                ('durability_max', models.IntegerField(default=100, verbose_name='Прочность')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Катушка',
                'verbose_name_plural': 'Катушки',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='RodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='tackle/rods/', verbose_name='Изображение')),
                ('rod_class', models.CharField(choices=[('float', 'Поплавочное'), ('spinning', 'Спиннинговое'), ('bottom', 'Донное')], max_length=20, verbose_name='Класс')),
                ('test_min', models.FloatField(verbose_name='Тест мин (кг)')),
                ('test_max', models.FloatField(verbose_name='Тест макс (кг)')),
                ('durability_max', models.IntegerField(default=100, verbose_name='Прочность')),
                ('length', models.FloatField(verbose_name='Длина (м)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('min_rank', models.IntegerField(default=1, verbose_name='Мин. разряд')),
            ],
            options={
                'verbose_name': 'Удилище',
                'verbose_name_plural': 'Удилища',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Bait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='tackle/baits/', verbose_name='Изображение')),
                ('quantity_per_pack', models.IntegerField(default=20, verbose_name='Кол-во в упаковке')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('target_species', models.ManyToManyField(blank=True, to='tackle.fishspecies', verbose_name='Целевые виды')),
            ],
            options={
                'verbose_name': 'Наживка',
                'verbose_name_plural': 'Наживки',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Flavoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='tackle/flavorings/', verbose_name='Изображение')),
                ('bonus_multiplier', models.FloatField(default=1.2, verbose_name='Множитель бонуса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('target_species', models.ManyToManyField(blank=True, to='tackle.fishspecies', verbose_name='Целевые виды')),
            ],
            options={
                'verbose_name': 'Ароматизатор',
                'verbose_name_plural': 'Ароматизаторы',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Groundbait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='tackle/groundbaits/', verbose_name='Изображение')),
                ('effectiveness', models.IntegerField(default=5, verbose_name='Эффективность (1-10)')),
                ('duration_hours', models.IntegerField(default=3, verbose_name='Длительность (игр. часов)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('target_species', models.ManyToManyField(blank=True, to='tackle.fishspecies', verbose_name='Целевые виды')),
            ],
            options={
                'verbose_name': 'Прикормка',
                'verbose_name_plural': 'Прикормки',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Lure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='tackle/lures/', verbose_name='Изображение')),
                ('lure_type', models.CharField(choices=[('spoon', 'Колебалка'), ('wobbler', 'Воблер'), ('jig', 'Джиг'), ('soft', 'Силикон')], max_length=20, verbose_name='Тип')),
                ('depth_min', models.FloatField(default=0.5, verbose_name='Мин. глубина проводки (м)')),
                ('depth_max', models.FloatField(default=3.0, verbose_name='Макс. глубина проводки (м)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('target_species', models.ManyToManyField(blank=True, to='tackle.fishspecies', verbose_name='Целевые виды')),
            ],
            options={
                'verbose_name': 'Приманка',
                'verbose_name_plural': 'Приманки',
                'ordering': ['price'],
            },
        ),
    ]
