# Generated by Django 5.2.11 on 2026-02-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tackle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hook',
            name='image',
            field=models.ImageField(blank=True, upload_to='tackle/hooks/', verbose_name='Изображение'),
        ),
    ]
