# Generated by Django 5.2.11 on 2026-02-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_playerrod_lure_and_more'),
        ('tackle', '0003_fishpricedynamic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodtype',
            name='rod_class',
            field=models.CharField(choices=[('float', 'Поплавочное'), ('bottom', 'Донное')], max_length=20, verbose_name='Класс'),
        ),
        migrations.DeleteModel(
            name='Lure',
        ),
    ]
