# Generated by Django 5.2.11 on 2026-02-16 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='Никнейм')),
                ('rank', models.IntegerField(default=1, verbose_name='Разряд')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт')),
                ('karma', models.IntegerField(default=0, verbose_name='Карма')),
                ('money', models.DecimalField(decimal_places=2, default=500.0, max_digits=12, verbose_name='Деньги')),
                ('gold', models.IntegerField(default=0, verbose_name='Голд (премиум)')),
                ('hunger', models.IntegerField(default=100, verbose_name='Сытость (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('current_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='world.base', verbose_name='Текущая база')),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='world.location', verbose_name='Текущая локация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
    ]
