# Generated by Django 5.2.11 on 2026-02-16 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0003_playerrod_clip_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rod_slot_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_slot_1', to='inventory.playerrod', verbose_name='Слот удочки 1'),
        ),
        migrations.AddField(
            model_name='player',
            name='rod_slot_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_slot_2', to='inventory.playerrod', verbose_name='Слот удочки 2'),
        ),
        migrations.AddField(
            model_name='player',
            name='rod_slot_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_slot_3', to='inventory.playerrod', verbose_name='Слот удочки 3'),
        ),
    ]
