# Generated by Django 5.2.11 on 2026-02-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_player_rod_slot_1_player_rod_slot_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApparatusPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Деталь аппарата',
                'verbose_name_plural': 'Детали аппарата',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MoonshineIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='MoonshineRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('effect_type', models.CharField(choices=[('bite_boost', 'Поклёвка +25%'), ('experience_boost', 'Опыт +30%'), ('hunger_restore', 'Восстановление сытости'), ('luck', 'Удача (редкие рыбы)')], max_length=20, verbose_name='Тип эффекта')),
                ('effect_value', models.FloatField(default=0.25, verbose_name='Сила эффекта')),
                ('duration_hours', models.IntegerField(default=6, verbose_name='Длительность (игр. часов)')),
                ('crafting_time_hours', models.IntegerField(default=3, verbose_name='Время варки (игр. часов)')),
                ('required_ingredients', models.JSONField(default=dict, help_text='{"sugar": 3, "yeast": 1}', verbose_name='Необходимые ингредиенты')),
            ],
            options={
                'verbose_name': 'Рецепт самогона',
                'verbose_name_plural': 'Рецепты самогона',
            },
        ),
        migrations.CreateModel(
            name='BrewingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('brewing', 'Варится'), ('ready', 'Готов')], default='brewing', max_length=10, verbose_name='Статус')),
                ('started_at_hour', models.IntegerField(verbose_name='Час начала (игровой)')),
                ('started_at_day', models.IntegerField(verbose_name='День начала (игровой)')),
                ('ready_at_hour', models.IntegerField(verbose_name='Час готовности (игровой)')),
                ('ready_at_day', models.IntegerField(verbose_name='День готовности (игровой)')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brewing_sessions', to='accounts.player')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.moonshinerecipe')),
            ],
            options={
                'verbose_name': 'Сессия варки',
                'verbose_name_plural': 'Сессии варки',
            },
        ),
        migrations.CreateModel(
            name='PlayerMoonshineBuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at_hour', models.IntegerField(verbose_name='Час активации (игровой)')),
                ('activated_at_day', models.IntegerField(verbose_name='День активации (игровой)')),
                ('expires_at_hour', models.IntegerField(verbose_name='Час истечения (игровой)')),
                ('expires_at_day', models.IntegerField(verbose_name='День истечения (игровой)')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moonshine_buffs', to='accounts.player')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.moonshinerecipe')),
            ],
            options={
                'verbose_name': 'Бафф самогона',
                'verbose_name_plural': 'Баффы самогона',
            },
        ),
        migrations.CreateModel(
            name='PlayerApparatusPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.apparatuspart')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apparatus_parts', to='accounts.player')),
            ],
            options={
                'verbose_name': 'Деталь аппарата игрока',
                'verbose_name_plural': 'Детали аппарата игроков',
                'unique_together': {('player', 'part')},
            },
        ),
        migrations.CreateModel(
            name='PlayerIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.moonshineingredient')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='accounts.player')),
            ],
            options={
                'verbose_name': 'Ингредиент игрока',
                'verbose_name_plural': 'Ингредиенты игроков',
                'unique_together': {('player', 'ingredient')},
            },
        ),
    ]
