# Generated by Django 5.2.11 on 2026-02-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tackle', '0001_initial'),
        ('teams', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('tournament_type', models.CharField(choices=[('individual', 'Индивидуальный'), ('team', 'Командный')], default='individual', max_length=20, verbose_name='Тип турнира')),
                ('scoring', models.CharField(choices=[('weight', 'По весу'), ('count', 'По количеству'), ('specific_fish', 'По конкретной рыбе')], default='weight', max_length=20, verbose_name='Система подсчёта')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('end_time', models.DateTimeField(verbose_name='Окончание')),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вступительный взнос')),
                ('prize_money', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Призовой фонд')),
                ('prize_experience', models.IntegerField(default=0, verbose_name='Призовой опыт')),
                ('prize_karma', models.IntegerField(default=0, verbose_name='Призовая карма')),
                ('min_rank', models.IntegerField(default=1, verbose_name='Мин. разряд')),
                ('max_participants', models.IntegerField(default=100, verbose_name='Макс. участников')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Завершён')),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='world.location', verbose_name='Целевая локация')),
                ('target_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='tackle.fishspecies', verbose_name='Целевой вид рыбы')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TournamentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='Очки')),
                ('fish_count', models.IntegerField(default=0, verbose_name='Количество рыб')),
                ('rank_position', models.IntegerField(default=0, verbose_name='Место')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to='accounts.player', verbose_name='Игрок')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_entries', to='teams.team', verbose_name='Команда')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Участие в турнире',
                'verbose_name_plural': 'Участия в турнирах',
                'unique_together': {('tournament', 'player')},
            },
        ),
    ]
