# Generated by Django 5.2.11 on 2026-02-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tackle', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(choices=[('catch', 'Поимка'), ('record', 'Рекорд'), ('quest', 'Квест'), ('rank', 'Разряд'), ('karma', 'Карма'), ('special', 'Особое')], max_length=20, verbose_name='Категория')),
                ('icon', models.CharField(default='🏆', max_length=10, verbose_name='Иконка (emoji)')),
                ('condition_type', models.CharField(help_text='fish_count, species_count, total_weight, rank, karma, quest_count, record', max_length=50, verbose_name='Тип условия')),
                ('condition_value', models.IntegerField(default=1, verbose_name='Значение условия')),
                ('reward_money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Награда (деньги)')),
                ('reward_experience', models.IntegerField(default=0, verbose_name='Награда (опыт)')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['category', 'condition_value'],
            },
        ),
        migrations.CreateModel(
            name='FishRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('length', models.FloatField(verbose_name='Длина (см)')),
                ('caught_at', models.DateTimeField(auto_now_add=True, verbose_name='Время поимки')),
                ('is_weekly_champion', models.BooleanField(default=False, verbose_name='Рекордсмен недели')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.location')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='accounts.player')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tackle.fishspecies')),
            ],
            options={
                'verbose_name': 'Рекорд',
                'verbose_name_plural': 'Рекорды',
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Разблокировано')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_achievements', to='records.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='accounts.player')),
            ],
            options={
                'verbose_name': 'Достижение игрока',
                'verbose_name_plural': 'Достижения игроков',
                'unique_together': {('player', 'achievement')},
            },
        ),
    ]
