# Generated by Django 5.2.11 on 2026-02-18 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_player_rod_slot_1_player_rod_slot_2_and_more'),
        ('inventory', '0004_remove_playerrod_lure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('satiety', models.IntegerField(verbose_name='Сытость')),
                ('image', models.ImageField(blank=True, upload_to='bar/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Напитки',
            },
        ),
        migrations.CreateModel(
            name='BarSnackOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation', models.CharField(choices=[('dried', 'Сушёная'), ('smoked', 'Вяленая'), ('fried', 'Жареная')], max_length=10, verbose_name='Способ приготовления')),
                ('satiety_gained', models.IntegerField(verbose_name='Восстановлено сытости')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.caughtfish', verbose_name='Рыба')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_snacks', to='accounts.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Закуска из рыбы',
                'verbose_name_plural': 'Закуски из рыбы',
            },
        ),
    ]
