# Generated by Django 5.2.11 on 2026-02-18 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_player_rod_slot_1_player_rod_slot_2_and_more'),
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarDrinkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.bardrink', verbose_name='Напиток')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_drinks_ordered', to='accounts.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Заказ напитка',
                'verbose_name_plural': 'Заказы напитков',
            },
        ),
    ]
