# Generated by Django 5.2.11 on 2026-02-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_bardrinkorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bardrinkorder',
            name='game_day',
            field=models.IntegerField(default=1, verbose_name='Игровой день'),
        ),
    ]
