# Generated by Django 5.2.11 on 2026-02-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tackle', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('quest_type', models.CharField(choices=[('catch_fish', 'Поймать рыбу'), ('catch_weight', 'Поймать вес'), ('catch_species', 'Поймать вид')], max_length=20, verbose_name='Тип')),
                ('target_count', models.IntegerField(default=1, verbose_name='Целевое количество')),
                ('target_weight', models.FloatField(default=0, verbose_name='Целевой вес (кг)')),
                ('reward_money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Награда (деньги)')),
                ('reward_experience', models.IntegerField(default=0, verbose_name='Награда (опыт)')),
                ('reward_karma', models.IntegerField(default=0, verbose_name='Награда (карма)')),
                ('min_rank', models.IntegerField(default=1, verbose_name='Мин. разряд')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('prerequisite_quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quests.quest', verbose_name='Предварительный квест')),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.location', verbose_name='Целевая локация')),
                ('target_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tackle.fishspecies', verbose_name='Целевой вид')),
            ],
            options={
                'verbose_name': 'Квест',
                'verbose_name_plural': 'Квесты',
                'ordering': ['order', 'min_rank'],
            },
        ),
        migrations.CreateModel(
            name='PlayerQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, verbose_name='Прогресс')),
                ('progress_weight', models.FloatField(default=0, verbose_name='Прогресс (вес)')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершён'), ('claimed', 'Награда получена')], default='active', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начат')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='accounts.player')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_quests', to='quests.quest')),
            ],
            options={
                'verbose_name': 'Квест игрока',
                'verbose_name_plural': 'Квесты игроков',
                'unique_together': {('player', 'quest')},
            },
        ),
    ]
