# Generated by Django 5.2.11 on 2026-02-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='reward_apparatus_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.apparatuspart', verbose_name='Награда: деталь аппарата'),
        ),
    ]
