# Generated by Django 5.2.11 on 2026-02-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='channel',
            field=models.CharField(choices=[('location', 'Локация'), ('base', 'База'), ('global', 'Общий'), ('bar', 'Бар')], default='location', max_length=20, verbose_name='Канал'),
        ),
    ]
