# Generated by Django 5.2.11 on 2026-02-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Время проверки')),
                ('violation_found', models.BooleanField(default=False, verbose_name='Нарушение обнаружено')),
                ('violation_type', models.CharField(blank=True, choices=[('forbidden_species', 'Запрещённый вид'), ('size_limit', 'Размерное нарушение'), ('creel_limit', 'Превышение лимита садка')], max_length=30, verbose_name='Тип нарушения')),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма штрафа')),
                ('karma_penalty', models.IntegerField(default=0, verbose_name='Штраф кармы')),
                ('details', models.TextField(blank=True, verbose_name='Описание нарушения')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.location', verbose_name='Локация')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='accounts.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Проверка рыбнадзора',
                'verbose_name_plural': 'Проверки рыбнадзора',
                'ordering': ['-checked_at'],
            },
        ),
    ]
