# Generated by Django 5.2.11 on 2026-02-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tackle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='bases/', verbose_name='Изображение')),
                ('world_map_x', models.FloatField(default=0, verbose_name='X на карте мира')),
                ('world_map_y', models.FloatField(default=0, verbose_name='Y на карте мира')),
                ('min_rank', models.IntegerField(default=1, verbose_name='Мин. разряд')),
                ('min_karma', models.IntegerField(default=0, verbose_name='Мин. карма')),
                ('travel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость переезда')),
                ('requires_vehicle', models.BooleanField(default=False, verbose_name='Требует транспорт')),
            ],
            options={
                'verbose_name': 'База',
                'verbose_name_plural': 'Базы',
                'ordering': ['min_rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image_morning', models.ImageField(blank=True, upload_to='locations/', verbose_name='Изображение (утро)')),
                ('image_day', models.ImageField(blank=True, upload_to='locations/', verbose_name='Изображение (день)')),
                ('image_evening', models.ImageField(blank=True, upload_to='locations/', verbose_name='Изображение (вечер)')),
                ('image_night', models.ImageField(blank=True, upload_to='locations/', verbose_name='Изображение (ночь)')),
                ('depth_map', models.JSONField(blank=True, default=dict, verbose_name='Карта глубин')),
                ('min_rank', models.IntegerField(default=1, verbose_name='Мин. разряд')),
                ('requires_ticket', models.BooleanField(default=False, verbose_name='Требует путёвку')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='world.base', verbose_name='База')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['base', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LocationFish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spawn_weight', models.FloatField(default=0.5, help_text='Относительная вероятность', verbose_name='Вес спавна (0-1)')),
                ('depth_preference', models.FloatField(default=2.0, verbose_name='Предпочтительная глубина (м)')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_fish', to='tackle.fishspecies')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_fish', to='world.location')),
            ],
            options={
                'verbose_name': 'Рыба на локации',
                'verbose_name_plural': 'Рыбы на локациях',
                'unique_together': {('location', 'fish')},
            },
        ),
        migrations.AddField(
            model_name='location',
            name='fish_species',
            field=models.ManyToManyField(through='world.LocationFish', to='tackle.fishspecies', verbose_name='Виды рыб'),
        ),
    ]
