# Generated by Django 5.2.11 on 2026-02-16 09:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tackle', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FightState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_strength', models.FloatField(default=10.0, verbose_name='Сила рыбы')),
                ('line_tension', models.FloatField(default=0, verbose_name='Натяжение лески (0-100)')),
                ('distance', models.FloatField(default=20.0, verbose_name='Расстояние до берега (м)')),
                ('rod_durability', models.FloatField(default=100, verbose_name='Прочность удилища')),
                ('last_action_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время последнего действия')),
            ],
            options={
                'verbose_name': 'Состояние вываживания',
                'verbose_name_plural': 'Состояния вываживания',
            },
        ),
        migrations.CreateModel(
            name='GameTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hour', models.IntegerField(default=8, verbose_name='Текущий час (0-23)')),
                ('current_day', models.IntegerField(default=1, verbose_name='Текущий день')),
                ('last_tick', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последний тик')),
            ],
            options={
                'verbose_name': 'Игровое время',
                'verbose_name_plural': 'Игровое время',
            },
        ),
        migrations.CreateModel(
            name='GroundbaitSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Применено')),
                ('expires_at_hour', models.IntegerField(default=0, verbose_name='Истекает (игровой час)')),
                ('expires_at_day', models.IntegerField(default=0, verbose_name='Истекает (игровой день)')),
            ],
            options={
                'verbose_name': 'Точка прикорма',
                'verbose_name_plural': 'Точки прикорма',
            },
        ),
        migrations.CreateModel(
            name='FishingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('idle', 'Без дела'), ('waiting', 'Ожидание поклёвки'), ('bite', 'Поклёвка!'), ('fighting', 'Вываживание'), ('caught', 'Рыба поймана')], default='idle', max_length=20, verbose_name='Состояние')),
                ('cast_x', models.FloatField(default=0, verbose_name='Точка заброса X')),
                ('cast_y', models.FloatField(default=0, verbose_name='Точка заброса Y')),
                ('cast_time', models.DateTimeField(blank=True, null=True, verbose_name='Время заброса')),
                ('bite_time', models.DateTimeField(blank=True, null=True, verbose_name='Время поклёвки')),
                ('hooked_weight', models.FloatField(blank=True, null=True, verbose_name='Вес клюнувшей рыбы')),
                ('hooked_length', models.FloatField(blank=True, null=True, verbose_name='Длина клюнувшей рыбы')),
                ('hooked_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tackle.fishspecies', verbose_name='Клюнувшая рыба')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.location', verbose_name='Локация')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fishing_session', to='accounts.player')),
            ],
            options={
                'verbose_name': 'Сессия рыбалки',
                'verbose_name_plural': 'Сессии рыбалки',
            },
        ),
    ]
