# Generated by Django 5.2.11 on 2026-02-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('fishing', '0001_initial'),
        ('inventory', '0001_initial'),
        ('tackle', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingsession',
            name='rod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.playerrod', verbose_name='Снасть'),
        ),
        migrations.AddField(
            model_name='fightstate',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fight', to='fishing.fishingsession'),
        ),
        migrations.AddField(
            model_name='groundbaitspot',
            name='flavoring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tackle.flavoring', verbose_name='Ароматизатор'),
        ),
        migrations.AddField(
            model_name='groundbaitspot',
            name='groundbait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tackle.groundbait', verbose_name='Прикормка'),
        ),
        migrations.AddField(
            model_name='groundbaitspot',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.location'),
        ),
        migrations.AddField(
            model_name='groundbaitspot',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groundbait_spots', to='accounts.player'),
        ),
    ]
