# Generated by Django 5.2.11 on 2026-02-16 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('fishing', '0002_initial'),
        ('inventory', '0001_initial'),
        ('tackle', '0002_add_hook_image'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingsession',
            name='slot',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Слот удочки'),
        ),
        migrations.AlterField(
            model_name='fishingsession',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishing_sessions', to='accounts.player'),
        ),
        migrations.AddConstraint(
            model_name='fishingsession',
            constraint=models.UniqueConstraint(fields=('player', 'rod'), name='unique_player_rod_session'),
        ),
        migrations.AddConstraint(
            model_name='fishingsession',
            constraint=models.UniqueConstraint(fields=('player', 'slot'), name='unique_player_slot_session'),
        ),
    ]
