# Generated by Django 5.2.11 on 2026-02-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0003_fishingsession_slot_alter_fishingsession_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingsession',
            name='slot',
            field=models.PositiveSmallIntegerField(db_default=1, default=1, verbose_name='Слот удочки'),
        ),
    ]
