# Generated by Django 5.2.11 on 2026-02-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0004_alter_fishingsession_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingsession',
            name='is_retrieving',
            field=models.BooleanField(default=False, verbose_name='Проводка (для спиннинга)'),
        ),
    ]
