# Generated by Django 5.2.11 on 2026-02-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0005_fishingsession_is_retrieving'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingsession',
            name='retrieve_progress',
            field=models.FloatField(default=0.0, verbose_name='Прогресс подматывания (0-1)'),
        ),
    ]
