# Generated by Django 5.2.11 on 2026-02-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0007_remove_unique_session_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingsession',
            name='bite_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Длительность поклёвки (сек)'),
        ),
        migrations.AddField(
            model_name='fishingsession',
            name='nibble_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Длительность подёргивания (сек)'),
        ),
        migrations.AddField(
            model_name='fishingsession',
            name='nibble_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала подёргивания'),
        ),
        migrations.AlterField(
            model_name='fishingsession',
            name='state',
            field=models.CharField(choices=[('idle', 'Без дела'), ('waiting', 'Ожидание поклёвки'), ('nibble', 'Подёргивание'), ('bite', 'Поклёвка!'), ('fighting', 'Вываживание'), ('caught', 'Рыба поймана')], default='idle', max_length=20, verbose_name='Состояние'),
        ),
    ]
