# Generated by Django 5.2.11 on 2026-02-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0008_add_nibble_state_and_timers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishingsession',
            name='is_retrieving',
        ),
        migrations.RemoveField(
            model_name='fishingsession',
            name='retrieve_progress',
        ),
    ]
